### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by genesixx** [fxbabin/fractol#1]
crash : 0

**Comment by fxbabin** [comment]
de façon a pouvoir vous aider cher monsieur il faut préciser où se trouve le segfault sans quoi il est difficile de le réparer. En tout cas félicitations pour votre projet eczema !

**Comment by genesixx** [comment]
bonsoir je pense que le segfault est a la ligne 3 du readme. mais je peux me tromper je suis humain avant tout. et merci ca gratte fort
